name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # ajuste para o nome da sua branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/concoordpro
        run: |
          docker build . -t $IMAGE
          docker push $IMAGE

      - name: Deploy to Cloud Run
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          REGION: us-central1  # ajuste para a região desejada
          SERVICE_NAME: nome-do-seu-servico
          IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/concoordpro
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image $IMAGE \
            --platform managed \
            --region $REGION \
            --allow-unauthenticated
